FROM python:3.8-slim

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

WORKDIR /opt/dagster/app

COPY aero_dagster ./aero_dagster
COPY connector    ./connector


# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "--package-name", "aero_dagster"]